version: '3.5'
services:
  db:
    container_name: tm_database
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - 5432:5432
  server:
    container_name: tm_server
    build:
      context: server
      dockerfile: Dockerfile
    depends_on:
      - db
  web:
    container_name: tm_web
    build:
      context: ../TMFrontend
      dockerfile: Dockerfile
    ports:
      - 8080:4200
