version: '3.5'
services:
  db:
    container_name: tm_database
    build:
      context: db
      dockerfile: Dockerfile
    networks:
      - tm_network
    expose:
      - "5432"
#    ports:
#      - 5432:5432
  server:
    container_name: tm_server
    build:
      context: server
      dockerfile: Dockerfile
    expose:
      - "8080"
    networks:
      - tm_network
    depends_on:
      - db
  web:
    container_name: tm_web
    build:
      context: ../TMFrontend
      dockerfile: Dockerfile
    ports:
      - 8090:4200
    networks:
      - tm_network

networks:
  tm_network:
    driver: bridge